steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "cloud/Dockerfile", "-t", "${_IMAGE}", "."]
images: ["${_IMAGE}"]
substitutions:
  _IMAGE: asia-south1-docker.pkg.dev/${PROJECT_ID}/sahayak/cloud:latest
options:
  machineType: E2_HIGHCPU_8
